### ISSUE TITLE
Fix progress percentage in questionnaire

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#125]

**Comment by drdavec** [comment]
The current design for progress percent was inherited from the MyPain app implementation. However, this design was very specific to that one questionnaire design where the itemId incremented from 1, 2, 3, etc.  This is unlikely in other questionnaires.

More design and development work is needed to create a generalizable progress indicator.  Marking this as an enhancement rather than a bug.  And removing the progress indicator until redesign is completed.

**Comment by kbertodatti** [comment]
Looks like progress indicator was removed so it's no longer a problem.
