### ISSUE TITLE
Create FHIR Questionnaire for Caregiver Strain Index 

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#132]
This is now in the updated build and available for testing in both CarePlanning and QA sandboxes.

**Comment by demritoop** [comment]
1. Question 1: Question 1 has ellipses after "because" and the statement is poorly phrased. Potentially change it to "Sleep is disturbed (e.g., because patient is in and out of bed; wanders around at night"?
2. Question 2: Change "it's" to "it is".
3.  Question 8: Ellipses should be removed in both statements.
4. Question 9: Sentence is poorly phrased. Potentially change it to "It is upsetting the patient has changed so much from his/her former self (e.g., he/she is a different person than he/she used to be".
5. Question 11: Awkward spacing between the start of the sentence and the beginning of the text box.
6. Question 11: The "Yes" and "No" boxes are out of alignment with the rest of the survey.
7. Question 12: Ellipses should be removed. Potentially rephrase statement to "e.g., because of worry about the patient; concerns about how you will manage".

**Comment by drdavec** [comment]
Thanks for your detailed review @demritoop!  Also @kbertodatti When creating a FHIR questionnaire from a standard research instrument, I am very careful to copy the question text exactly as written.  Including the ellipses in this case.  I will look at the formatting issues you noted for question 11.  But otherwise, can you send an email to Katie and Carole asking whether they would recommend using the Caregiver Strain Index exactly as written in the PDF?
