### ISSUE TITLE
Fix formatting for Q11 in Caregiver Strain Index

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#134]
Question 11 in the Caregiver Strain Index questionnaire seems to be off compared to the formatting of the rest of the questions. Is there a way to fix?

![image.png](https://images.zenhubusercontent.com/6197ef7a2c4a0098cd7694e6/a473ea41-da0c-4646-beea-7d5af127678d)

**Comment by kbertodatti** [comment]
@drbgfc is this a quick fix?

**Comment by drbgfc** [comment]
I'd have to take a look but I can't imagine it taking long. A FormGroup might resolve it.
When I take a look, so that it's quicker, where does the content come from?

**Comment by kbertodatti** [comment]
It's on the Home tab, under "My Tasks" --> "Caregiver Strain Assessment"

**Comment by drbgfc** [comment]
Great, that's helpful, I can figure it out from there. I was asking though, not clearly, where the static content is derived from in the source code.

**Comment by kbertodatti** [comment]
Oh, lol. I think @drdavec had to make it...but either way, Dave can answer that question.

**Comment by drbgfc** [comment]
"Dave Carlson
  [7:26 PM](https://mcc-ecare.slack.com/archives/C03T9LN93NJ/p1670372819121059)
The text content for all questionnaires is from a FHIR Questionnaire resource.  For this one, see https://github.com/chronic-care/mycareplanner/blob/develop/public/content/caregiver-strain-questionnaire.json
[caregiver-strain-questionnaire.json](https://github.com/chronic-care/mycareplanner/blob/develop/public/content/caregiver-strain-questionnaire.json)
```
{
   "resourceType": "Questionnaire",
   "id": "questionnaire-caregiver-strain-index",
   "url": "http://hl7.org/Questionnaire/caregiver-strain-index",
Show more
<https://github.com/[chronic-care/mycareplanner](https://github.com/chronic-care/mycareplanner)|chronic-care/mycareplanner>chronic-care/mycareplanner | Added by [GitHub](https://mcc-ecare.slack.com/services/B03NR95652Q)"

**Comment by drbgfc** [comment]
Dave Carlson
  [7:28 PM](https://mcc-ecare.slack.com/archives/C03T9LN93NJ/p1670372936382179)
Looking at this issue, I suspect the text is being centered, and this question has a short string so is centered in the space available.  Other long strings are wrapped.  But just a guess from the screenshot
:+1:
1



Dan Brown
  [7:30 PM](https://mcc-ecare.slack.com/archives/C03T9LN93NJ/p1670373019527609)
Yeah, w/e is happening is not specific to this one item since they are dynamically created. Could indeed be centering. Definitely seen due to the shorter string.
New


Dave Carlson
  [7:32 PM](https://mcc-ecare.slack.com/archives/C03T9LN93NJ/p1670373147126699)
I borrowed the initial questionnaire rendering from another project, then expanded to support additional question types.  This logic definitely needs to be cleaned up.  https://github.com/chronic-care/mycareplanner/tree/develop/src/components/questionnaire-item

**Comment by kbertodatti** [comment]
@drdavec to update build of the app to include this and push into QA sandbox.

**Comment by kbertodatti** [comment]
Fixed! ![image.png](https://images.zenhubusercontent.com/6197ef7a2c4a0098cd7694e6/e0218d5d-6f2a-4f00-b046-f17ec3c17b55)
