### ISSUE TITLE
Review and merge tab redesign into patient/caregiver app

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#199]
please review and merge the new tab UI in https://github.com/chronic-care/mycareplanner/pull/13/files as soon as you can so we can keep it in sync with develop (w/o another conflict) and create a new branch for 
@mark.koyanagi
 and 
@Yujiemi Chisholm
 to work on the footer from

**Comment by drbgfc** [comment]
For this ticket, I've resolved merge isssues so it's just a matter of making sure you're happy with the new look/feel (of course, we can always change that with css or sx styling) and clicking the merge button. If you'd prefer I jcan ust merge in the future, let me know. I think in this case I probably should have because we want to use MUI anyway. Just wanted to give you the chance to review before it became a part of develop. Thanks.

**Comment by kbertodatti** [comment]
@drdavec - see Dan's comment above.

**Comment by kbertodatti** [comment]
From @drdavec :

I set up some comparison tests of the current app tab design, compared with the revised tabs design implemented by the RTI UI team.  You can see the current tab design here:
https://chronic-care.github.io/mycareplanner/launch.html?iss=https://gw.interop.community/CarePlanning/data
And the updated tab design here (contains "-qa" in the app path):
https://chronic-care.github.io/mycareplanner-qa/launch.html?iss=https://gw.interop.community/CarePlanning/data

**Comment by kbertodatti** [comment]
Questions:
* Caps in the upper tabs
* Any way to minimize space of the lower navigation (it looks smaller in the design). Maybe reduce icon size and/or margin?
* Relook at margins overall. Do we need margins that wide (left and right outside of card).
