### ISSUE TITLE
Add Gravity value sets to Health Concerns list in provider app

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#202]
For problem list item that has a code that's in the Gravity Value Set, then display code.

**Comment by drdavec** [comment]
If we would like social risks and health concerned display in the Health Concerns section, instead of or in addition to the Problem List section, then we must use the Gravity condition value sets to classify the Condition resources.  The Condition.category was used previously, but we cannot expect to find this populated in current EHR endpoints.

US Core also should have a grouped value set that includes all SDoH codes, or use the separate value sets from Gravity.  Check with Himali for recommended alternative.  If Condition.code is present in an SDoH value set, then display in the Health Concerns section of provider app.
