### ISSUE TITLE
Data aggregation for multiple logins

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#215]
Combine data from all endpoints.
Ensure the display is accurate.

Make sure we have one design that works in both apps. Coordinate with @drdavec and @svalluripalli 

Sequence of cards:
#214
#217
#215
#240

**Comment by iks1** [comment]
why is the repo empty ? :0

**Comment by drbgfc** [comment]
> why is the repo empty ? :0

Not sure what you mean? It's not empty, were you looking to contribute? I'm sure one of us can guide you.

**Comment by savanahmueller** [comment]
@Dave Carlson
for data aggregation we have a note to complete in this order:
aggregate the data within the app
process each provider data set using CQL and then display the aggregated CQL results
I'm wondering why we cannot/should not complete in this order:
Process data with CQL from 1st provider
Process data with CQL from 2nd provider
Aggregate data
Display

Also, FYI, update in dev allows selection of one or more providers. At this time I have disabled more than one until aggregation is implemented

Are we intending to support the aggregation of two different patients? For example, in testing, all of our providers have different patients. In the real world, if they are 2 different people, what should we do?

3 options for data aggregation and a couple of alternatives:
1: Create arrays of all of our major data items (fhirData, patientSummary, etc.) so we will have something like [fhirData1, fhirData2, fhireData3] and then update all display code (and edit code) to work with this new system
2: Update the actual interfaces have an array value for each property and have one huge version of each major data item. So, fhirData won't be an array, but, it will have a bunch of properties that are all arrays or arrays of arrays. Won't require as much display code change, but will require a lot of logic changes due to the interfaces changing.
3: Convert and display on the fly in an adhoc manner (don't really like this idea from a maintenance perspective and would need a new combined interface)
X: Any combination of prior but editing CQL instead of data after CQL is run
I think item 1 or maybe item X combined with the style of 1 are the only feasible options from a maintainability and from a perspective of breaking the least amount of (important) stuff/less regression needed. All are complex (require widespread changes). However, feel free to chime in, hence why I'm throwing this out there.
X2: There is also the option of (or in addition) to turn fhirData, etc, into classes vs interfaces and adding methods for dynamic manipulation. I'm not so sure how relevant this is though, when having separate instances in an array. It depends on the complexity of the data. For instance, is it enough to simply have one set of data follow another in the display, or does it get more complex than that? If so, may need to consider a class along with option 2 or some other complex setup (e.g. instead of arrays for all properties we have more complex objects within them). We could also only have that type of situation where needed and update the interface as such.

**Comment by kbertodatti** [comment]
Dan is working on aggregating summary data (not FHIR data) into 2D array. Then work on displaying one in a summary. Others can be delegated using the summary dan does as a model.

Work on in parallel: The view for aggregated raw FHIR data can be displayed (the data that does not need to go through CQL). "FHIR data collection"- write display code to display it.
