### ISSUE TITLE
Fix variable width of the gray box when app is loading or where there is no data

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#236]
This sort of issue can be seen while viewing the following screens:

Care Plan > Goals
Care Plan > Medications
Health Status > Tests
Team
 
I suspect this is caused by a CSS min-width property not being set in the content pane, as the bug appears to only show up when there isn’t data to display and that content space is laterally collapsed.

![image001.png](https://images.zenhubusercontent.com/6197ef7a2c4a0098cd7694e6/d37b8093-e8e1-422d-bc93-2e0a94e52247)![image003.png](https://images.zenhubusercontent.com/6197ef7a2c4a0098cd7694e6/72eb590c-e9ad-4c12-b83f-c0fea7608f35)

**Comment by kbertodatti** [comment]
Dave update: Did some investigation of this but is not seeing anything in the CSS...so maybe this is something in the MUI?
Dan: Confirm you looked in all the CSS sheets in the hierarchy. Use !Important directly after the property name.

**Comment by drbgfc** [comment]
Add it after the property value.
For example, try this:
    min-width: 100% !important;

then this if no luck:
    min-width: 100% !important;
    width: auto !important;

then this if no luck:
    min-width: 100% !important;
    width: 100% !important;

Lots could be going on (and I haven't seen the code) so this might help you get there. Even though it is hacky until we normalize things.

Otherwise look into margin on the outer container or maybe even padding (depends on the system in use)

**Comment by savanahmueller** [comment]
I QA'd with two different patients. No change in the box length. Looks resolved.
