### ISSUE TITLE
Refine CQL process to save results in MyCarePlanner

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#262]
Save the results after running CQL process - for each endpoint.

Performance issue reported by pilots team.  I expect that this will be mostly fixed by caching the results of CQL execution for each  tab view content.  Currently, the CQL is re-executed each time a tab is visited, sometimes with several seconds delay.

From pilot team email:
performance is still a major issue. Dr. Dorr wrote from his recent experience testing the app:
It’s still amazingly slow. The initial load page isn’t too bad, but clicking through each page is at least 5 seconds – one it told me the ‘page was unresponsive’.
It also doesn’t retain data from any but the last 2 or 3 subpages, so has to reload frequently.
Dr. Dorr requests to know if we can devote more resources to addressing these performance issues, as he’s meeting with Arlene next week and wants to communicate realistic expectations.

**Comment by drbgfc** [comment]
Adding convos from slack:
Dan Brown
  4:09 PM
Interesting. Some thoughts.
-CQL cache will help, we should definitely do that.
-They are (now?) content with initial load even though it's not faster. So, I think that is due to progress. Maybe, as strange as it seems, adding determinant progress to the tabs may help it feel faster
-After the RTI UI updates lag was introduced within the tab changes where it appears that they are freezing (blocking the UI). That is probably what causes it to say page is unresponsive for large data. That has to be fixed so that we can properly display progress. That side effect of the update has always bothered me. It may require a react version update. But it will require some looking into, since it is related to 3rd party code (meaning the MUI API).
-We should introduce workers so we can have more loading happening in the background
-We may want to progressively display results if possible, vs just having a progress bar
New


Dave Carlson
  5:51 PM
@Dan Brown
 all good ideas!  You added useEffect() into each tab view, which I believe is executed every time a tab is selected.  For conditions, and same for all others, a method like getConditionSummary() is executed that loads and runs CQL.  The results, e.g. ConditionSummary[], should be cached and not recomputed on each view.
5:56
For workers, this package may be helpful:
https://github.com/asbi-cds-tools/cql-worker
asbi-cds-tools/cql-worker
A library for executing Clinical Quality Language (CQL) expressions asynchronously via Web Workers.
Stars
4
Language
JavaScript
Added by GitHub
