### ISSUE TITLE
See goals/concerns in MyCarePlanner saved in SDS (from previous sessions)

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/mcc-project#271]
As a patient, I want to see the goals/concerns I wrote and saved in MyCarePlanner (from previous sessions)
 enhance patient app to read patient authored content from SDS
To read patient/caregiver authored content saved in the SDS local partition. This includes goals and health concerns.

**Comment by kbertodatti** [comment]
issue when you read is that you need to connect to a specific patient

**Comment by kbertodatti** [comment]
Problem being able to read goals/concerns from the SDS. @drdavec will connect with @drbgfc to continue troubleshooting.

**Comment by kbertodatti** [comment]
Dan trying some additional approaches to attempt to resolve the issue.

**Comment by savanahmueller** [comment]
Implementing open endpoint version first for proving functionality. Then blocked by #

**Comment by kbertodatti** [comment]
From @drbgfc :
-The launcher is now dynamic. It can be derived from the client state itself and persisted appropriately upon leaving/returning to the app. It does not need to exist in the drop down (in the availableEndpoints). For example, if you don't have the launcher in the dropdown, and you load Meld as a launcher, you get meld. Then you add Epic and cerner as additional providers, and you get launcher + epic + cerner. This fixes the issue you've been talking about Sean with server A B C etc. In order to test it one must have a launcher that's not in additionalEndpoints, or, like I did, remove it with an env var. I removed Meld Test Data and tried that as the launcher for my tests.
-SDS is working but I haven't added the closed endpoint env vars. They should be able to be added but there may be some very minor adjustments needed. I saw your work, Dave. That was a cool test thanks for putting it out there. I think it needs more to cover all bases, though (as I'm sure you are aware), but thanks, again. It's interesting how you trigger the SDS via the launcher file itself. I hadn't thought of that. However, that would only work on a non-multi situation or first load I think? I haven't tested it that code you pushed. If not, and it can work for multi providers and all scenarios, it may be a cool trick we could incorporate in the final version. On my end in order to cover a heap of situations, there is a lot of new code/changes. So either way, plenty to integrate. Sean, have a blast on the merge (I feel for you)
--The SDS solution still needs work IMO. I mean, it will work, but things to consider are:
---Patient selection (partial impl)
---It's currently required to be defined in the availableEndpoints service, and, manually in one other location, but, with some thinking, that can be changed (I know have an example with the launcher). The manual location is probably fine though, in the long run. It's 'fine' because one just needs to provide the env vars and they propagate.
@Sean Muir
, you can merge from the branch on remote, called sds-read-and-dynamic-launcher, into develop. Please don't edit the branch itself though. You can always make a new branch off of it if you want to edit it directly. I want it to stay as as so I can add to it, and, so it can be seen that it does in fact, work, even if somewhat in progress.
https://github.com/chronic-care/mycareplanner/tree/sds-read-and-dynamic-launcher
General Note: This project is getting heavy into tech debt. I feel that I/we need to spend some hours on maintenance in the future (vs fixes for every assignment). Otherwise, it's just going to take longer in the future. I can think of many areas for improvement.
