### ISSUE TITLE
Add FHIR resource and time taken to load to indicate progress

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/mcc-project#276]
As FHIR queries are completed, display the query type, number of resources read, and the time taken.

Everything but the number is logged to the console already (not UI)

Display this in the home tab.

**Comment by drbgfc** [comment]
Pushed and update which displays realtime loading data to indicate progress. It handles various progress indicators including general progression, FHIR resources and timestamps, etc.

You can see the data under "Reading your clinical data" in Home.
It is followed by an elipses.

The same data is printed to the console in one function (less code), and is always prefixed by ProgressMessage.

If you'd like anything else displayed, I can certainly add it.

@drdavec Is the number of resources read something you expect to be displayed after everything has been read? If so, I'm not sure that's relevant to progress, as it implies the load is complete, and at that point, the data is displayed/we load what looks like a new page due to new data/text/links/etc.

**Comment by drbgfc** [comment]
I'll put in Review/QA for now since it can be tested from develop. But, Again, feel free to specifcy any updates to the new feature we might want.

@savanahmueller I think we should create a separate ticket to implement something similar, but for the display of errors (maybe below loading indications and in red). Errors should also likely stop the loading indication and let the error remain (along with some support contact message (do we have a support email I can use?))

**Comment by savanahmueller** [comment]
Hi Dan, I think creating a separate ticket to display that is a great idea.
Right now it is card #277 and we can edit it as needed.

As far as a support email, to my knowledge we do not have one. We do have a
meeting with the client today. Maybe this is something we can suggest? @Dave
Carlson ***@***.***> ?

Savanah Mueller, MPH, CPH, CHES

Senior Health Analyst

***@***.***

(410) 562-7695

LinkedIn <https://www.linkedin.com/company/emi-advisors-llc/mycompany/> |
Twitter <https://twitter.com/EMIadvisors> | emiadvisors.net
<https://www.emiadvisors.net/>



Did you know? Agencies now get "credit" for awards made to small businesses.

   -

   The Biden-Harris Administration is directing billions in government
   contracts
   <https://www.whitehouse.gov/briefing-room/statements-releases/2022/04/28/fact-sheet-the-small-business-boom-under-the-biden-harris-administration/>
   to small businesses.
   -

   As an SBA 8(a) <https://www.emiadvisors.net/contract-vehicles> small
   business, EMI welcomes the opportunity ***@***.***> to
   discuss how we can support you.

**Comment by savanahmueller** [comment]
Initial QA looks good. Loading progress bar. Does not show how far along, but it does show it is working. Tested with all 4 test patients.

**Comment by drbgfc** [comment]
Great, thanks!
There is always a near infinite amount of work that can be done. Figured I'd get a basic version out first since we have so many other priorites. IF you'd like to add other features such as the following list, or other ideas, let me know:
-Progress indication (vs continuous load) via an incremental progress bar tied to each task (it will only be an estimate, as each task can take any amount of time depending on patient records)
-Display of how many items have been completed overall, in realtime (what step we are in, or how many are left), again, these are estimates. Or, could be more specific, like count of resources loaded, like Dave mentioned (I think this is what you meant, vs a total at the end), in realtime. It's basically a count of each step that relevant. e.g. if we have loaded Medication and LabResult so far then # or resources loaded would display 2, then Social History is loaded and it updates to 3.

Need to decide if above should be a different ticket or not, to give time to higher priorities instead like multi login and loading performance. From what I understand, this should definitely take a back seat considering the complexity and priority of those items.

**Comment by savanahmueller** [comment]
I think a progress indicator bar would be helpful and a higher priority
than the display of # of items, but I will defer to Dave, Sean, and Sai on
that. I will make a new card (#278) in the backlog. We can discuss more
during sprint planning next week, or if it is more pressing, we can talk
during stand up tomorrow.

Savanah Mueller, MPH, CPH, CHES

Senior Health Analyst

***@***.***

(410) 562-7695

LinkedIn <https://www.linkedin.com/company/emi-advisors-llc/mycompany/> |
Twitter <https://twitter.com/EMIadvisors> | emiadvisors.net
<https://www.emiadvisors.net/>



Did you know? Agencies now get "credit" for awards made to small businesses.

   -

   The Biden-Harris Administration is directing billions in government
   contracts
   <https://www.whitehouse.gov/briefing-room/statements-releases/2022/04/28/fact-sheet-the-small-business-boom-under-the-biden-harris-administration/>
   to small businesses.
   -

   As an SBA 8(a) <https://www.emiadvisors.net/contract-vehicles> small
   business, EMI welcomes the opportunity ***@***.***> to
   discuss how we can support you.

**Comment by drbgfc** [comment]
Makes sense, I can do that
