### ISSUE TITLE
MyCarePlanner - should fail gracefully if patient data not found in SDS, or on SDS-related errors at startup

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#360]
MyCarePlanner in POC seems to now be hitting the SDS on launch.  This new behavior began with deployment of a supplemental release from EMI that added additional debug logging related to SDS interactions, I'm not sure why or how adding debug logging would have made this functionality work all of a sudden, but I'm not complaining.

In any case, MyCarePlanner loads patient data from OHSU, and then attempts to connect to the SDS to pull associated patient data, which is failing (we're presently debugging into this to sort out why).

![image](https://github.com/chronic-care/mcc-project/assets/979938/39715e99-dca6-4525-b77b-177816797b93)

However, what is important to note is that MyCarePlanner should handle cases where:
- Patient data cannot be found in the SDS
- The SDS throws an error during the request

It seems that MyCarePlanner is not handling those cases very well right now.  Instead of just displaying the already-acquired OHSU data, only error information is displayed on the home screen, and other screens display infinite "loading" progress bars, such as the following:

![image](https://github.com/chronic-care/mcc-project/assets/979938/fbfffd26-1041-43c0-a484-3c9a18d017ab)

**Comment by kbertodatti** [comment]
@drdavec need to have a conversation with you and @swmuir on how we want the workflow to work.

**Comment by kbertodatti** [comment]
Do first load with empty SDS - this works fine.
Do multi provider with empty SDS - this is an issue. 
Use valid SDS that has data, launch eCarePlanner which will automatically load SDS. From there go retrieve another provider. It should load launcher, SDS, and Epic. But it only loads Launcher and Epic (no SDS).
* Dave made a fix for this. Always add SDS to the list.
* @sean will review code to make sure that fix is in Dan's code.

**Comment by drbgfc** [comment]
Pushed fixes to develop on remote for:
1. Fix multi-provider SDS fails since SDS not always added to additionalProviders
2. Fix valid SDS pre-authorized providers not loading
3. Fail gracefully if patient data not found in SDS

Support empty SDS, other SDS fixes
https://github.com/chronic-care/mycareplanner/commit/e9885f98873c7f8ad01ca71e2d0a24855f7bf804

Issue 1 (#392) and 2 (#391) were pre-requisites/pre-existing issues to even start to address issue 3.

It's possible I didn't cover all scenarios for failing gracefully, but, it's well tested and in review.
Here are some of the scenarios I tested:

Define these SDS vars in env local:
REACT_APP_SHARED_DATA_ENDPOINT=https://gw.interop.community/eCareSharedData/open/
REACT_APP_SHARED_DATA_AUTH_ENDPOINT=https://gw.interop.community/CarePlanning/data
REACT_APP_SHARED_DATA_SCOPE=SET THIS DEPENDING ON TEST, SEE AHEAD
IMPORTANT, THIS IS EMPTY/commented out for these tests!
# REACT_APP_SHARED_DATA_CLIENT_ID=

Launcher is http://localhost:8000/mycareplanner/launch.html?iss=https://gw.interop.community/CarePlanning/data

# WORKING SDS:
REACT_APP_SHARED_DATA_ENDPOINT=https://gw.interop.community/eCareSharedData/open/

1. Launch with launcher
2. Ensure launch logic doesn't crash
3. Ensure launcher and SDS are shown/loaded on home
4. Ensure launcher and SDS are shown in relevant tabs
5. Click add additional providers
6. Add Epic
7. Ensure logic doesn't crash
8. Ensure launcher, SDS, and Epic are shown/loaded on home and shown in relevant tabs
9. Click add additional providers
10. Add Cerner
11: Ensure logic doesn't crash
12. Ensure launcher, SDS, and Cerner are shown/loaded on home and shown in relevant tabs
13. Click add additional providers
14. Add Epic and Cerner
15. Ensure logic doesn't crash
16. Ensure launcher, SDS, Epic, and Cerner are shown/loaded on home and shown in relevant tabs
17. Retest at different states of authorization for different resources (some are authorized already, some have expired)
18: Try re-selecting the same resources that were last selected vs new ones

# EMPTY SDS:
REACT_APP_SHARED_DATA_ENDPOINT=https://gw.interop.community/MCCSDSEmpty/open

1. Launch with launcher
2. Ensure launch logic doesn't crash and that empty SDS doesn't crash the application
3. Ensure launcher is shown and that SDS is NOT shown/loaded on home
4. Ensure launcher is shown and that SDS is NOT shown in relevant tabs
5. Click add additional providers
6. Add Epic
7. Ensure logic doesn't crash and that empty SDS doesn't crash the application
8. Ensure launcher and Epic are shown/loaded on home and shown in relevant tabs and that SDS is NOT shown/loaded
9. Click add additional providers
10. Add Cerner
11: Ensure logic doesn't crash
12. Ensure launcher, and Cerner are shown/loaded on home and shown in relevant tabs and that SDS is NOT shown/loaded
13. Click add additional providers
14. Add Epic and Cerner
15. Ensure logic doesn't crash
16. Ensure launcher, Epic, and Cerner are shown/loaded on home and shown in relevant tabs and that SDS is NOT shown/loaded
17. Retest at different states of authorization for different resources (some are authorized already, some have expired)
18: Try re-selecting the same resources that were last selected vs new ones
