### ISSUE TITLE
Revise FHIR query approach in eCarePlanner

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#393]
Investigate alternative query API that allows PatientID to be specified as a parameter instead of the .Patient with the library.

**Comment by drdavec** [comment]
I tested a revised use of FHIR query in MyCarePlanner and it works perfectly.  Pass the patientID as a query argument.
Use Client.request instead of  Client.patient.request

Instead of using:
let resourcePath = 'Condition?category=problem-list-item&clinical-status=active'
client.patient.request(resourcePath)

Use this:
const patientArgs = '&patient=' + client.patient.id   (or, use any other Patient.id instead of the one from client)
client.request(resourcePath+patientArgs)
