### ISSUE TITLE
Update session timeout to dump all tokens

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#426]
Step 1: Review code to see why the tokens aren't being cleared out now. (#425)
Step 2: Update code to dump all tokens and urls once session times out.

**Comment by drbgfc** [comment]
All local storage is cleared upon timeout (and soon enough, logout, same function).
Individual deletes are only needed if we for some reason cannot clear the sessionId or some other local storage key. if that's the case, we can just call the individual funtions I made in persistanceService, from handleLogout, instead of the delete all function it calls now.

**Comment by savanahmueller** [comment]
Can be QA'd at the same time at #330.
