### ISSUE TITLE
Create docker config for patient/caregiver app

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#98]
Create docker config.
Add ecareplan domain for patient/caregiver. Use my.ecareplan.org

**Comment by drdavec** [comment]
New requirement from RTI/OHSU, if possible:  Create a v2 patient app Docker config that appears to be the SAME APP as they deployed in v1, including:
* same client ID at OHSU
* same launch and redirect URLs

If possible, they would like to reuse the existing Epic app config, but launch the new v2 app.

**Comment by drdavec** [comment]
@swmuir After more discussion with RTI and OHSU, they decided that OHSU would like to allow both v1 and v2 patient apps to be available at the same time.  So the the v2 app should allow for a different app client ID in their Epic config and a different launch/redirect URL.

Please work with Matt at OHSU to test installation of the v2 app Docker.  They would like to get a proof-of-concept install running for testing differences from v1 for inviting patients to access the app.

**Comment by drdavec** [comment]
I don't know how custom deployment config files are included in Docker container so that OHSU can add their own app client ID.  I am using a .env.local file (which is not committed to GitHub for security of IDs).  How would they provide their own .env.local?  Matt said something about a file system directory outside of the Docker container?  I attached my .env.local used for testing and current deployment on GitHub.io

# Epic production client config
REACT_APP_CLIENT_ID_epic=ea547248-2c6b-4df5-aa52-847e17e19225

# Epic Sandbox for USCDI app
REACT_APP_CLIENT_ID_epic_sandbox=b62c9e05-83ac-4fd7-921d-7554e9b4d585

#Cerner sandbox
REACT_APP_CLIENT_ID_cerner=bd18953e-af7d-41b3-8585-58b0924a044f

# Logica
REACT_APP_CLIENT_ID_logica=7cbe9095-f665-4bee-8857-0451ddb72e90

# Meld
REACT_APP_CLIENT_ID_meld_mcc=2dbe1620-7232-4ab7-a5e5-4ee85112a74e

REACT_APP_CLIENT_ID_meld_qa=0e440b74-e49d-4975-9da7-a6afdea9e426
REACT_APP_CLIENT_ID_meld_synthea=2ce6fc18-6f3f-4e8a-b50f-540634aaf26b

# ACF ODH Sandbox
REACT_APP_CLIENT_ID_acf_odh=3dc692db-72eb-41a0-97ea-2e7d3a3b769d

**Comment by kbertodatti** [comment]
QA: when Matt Storer is able to run this.

**Comment by kbertodatti** [comment]
@swmuir docker name: mcc ecare
